### ISSUE TITLE
Help not split into Locale extension

### ISSUE THREAD

**Issue by wjt** [flathub/org.gnome.Gnote#3]
Around ¼ of this app is help in languages I don't understand:

```
~/.local/share/flatpak/app $ du --max-depth 1 -h \
> org.gnome.Gnote/current/active/files/share/{help,locale}
160K	org.gnome.Gnote/current/active/files/share/help/ru
448K	org.gnome.Gnote/current/active/files/share/help/fr
164K	org.gnome.Gnote/current/active/files/share/help/zh_CN
168K	org.gnome.Gnote/current/active/files/share/help/sv
740K	org.gnome.Gnote/current/active/files/share/help/de
1.4M	org.gnome.Gnote/current/active/files/share/help/lt
196K	org.gnome.Gnote/current/active/files/share/help/el
728K	org.gnome.Gnote/current/active/files/share/help/C
168K	org.gnome.Gnote/current/active/files/share/help/es
468K	org.gnome.Gnote/current/active/files/share/help/cs
160K	org.gnome.Gnote/current/active/files/share/help/hu
156K	org.gnome.Gnote/current/active/files/share/help/da
156K	org.gnome.Gnote/current/active/files/share/help/sl
5.0M	org.gnome.Gnote/current/active/files/share/help
60K	org.gnome.Gnote/current/active/files/share/locale/en_GB
64K	org.gnome.Gnote/current/active/files/share/locale
```

**Comment by wjt** [comment]
@nedrichards [said](https://github.com/flathub/org.gnome.Gnote/pull/2#issuecomment-392788123)

> Ideally that separate ticket would also go upstream.

I am not sure what the upstream ticket should be. Many applications install localised help within $prefix/lib/help. Is every Flatpak supposed to move this within the locale dir?

**Comment by nedrichards** [comment]
Ideally all apps would 'do the right thing' with help here, or flatpak would 'do the right thing' or (the worst case) something like Rob's suggestion of a [help extension](https://github.com/flathub/org.gnome.Gnote/pull/2#issuecomment-392789359) which you would then subset. Certainly if this behaviour is common then that means that any general solutions would get a significant space saving payback.
